/**
 * PostForge 主题定义
 * 每个主题定义一套排版样式，渲染时以内联 style 注入每个元素。
 * 新增主题只需在此追加一个对象。
 */

export const THEMES = {
  /**
   * clean — 中性简洁（默认）
   * 白底黑字，适合公众号 / 知乎 / 掘金 / CSDN 等绝大多数场景
   */
  clean: {
    id: 'clean',
    name: 'Clean 简洁（默认）',
    container: {
      color: '#3f3f3f',
      'font-family':
        '-apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
      'font-size': '15px',
      'line-height': '1.8',
      'letter-spacing': '0.3px',
      'word-spacing': '1px',
    },
    heading: {
      color: '#1a1a1a',
      'font-weight': '700',
      'line-height': '1.4',
      'margin-top': '28px',
      'margin-bottom': '14px',
    },
    h1: { 'font-size': '24px' },
    h2: { 'font-size': '21px' },
    h3: { 'font-size': '18px' },
    h4: { 'font-size': '16px' },
    h5: { 'font-size': '15px' },
    h6: { 'font-size': '14px' },
    paragraph: {
      'margin-top': '0',
      'margin-bottom': '16px',
      'text-align': 'justify',
    },
    strong: { color: '#1a1a1a', 'font-weight': '700' },
    em: { 'font-style': 'italic' },
    del: { 'text-decoration': 'line-through', color: '#999' },
    link: { color: '#576b95', 'text-decoration': 'none', 'word-break': 'break-all' },
    'inline-code': {
      color: '#c7254e',
      'background-color': '#f9f2f4',
      'font-family': '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
      'font-size': '90%',
      padding: '2px 5px',
      'border-radius': '3px',
    },
    codeblock: {
      'background-color': '#f6f8fa',
      'font-family': '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
      'font-size': '13px',
      'line-height': '1.6',
      padding: '14px 16px',
      'border-radius': '8px',
      'overflow-x': 'auto',
      color: '#24292e',
      'margin-top': '0',
      'margin-bottom': '16px',
      border: '1px solid #eaecef',
    },
    blockquote: {
      'border-left': '4px solid #dfe2e5',
      'background-color': '#f6f8fa',
      color: '#6a737d',
      padding: '12px 16px',
      'border-radius': '0 6px 6px 0',
      'margin-top': '0',
      'margin-bottom': '16px',
    },
    table: {
      'border-collapse': 'collapse',
      width: '100%',
      'font-size': '14px',
      'margin-top': '0',
      'margin-bottom': '16px',
    },
    th: {
      'background-color': '#f6f8fa',
      color: '#24292e',
      'font-weight': '600',
      'border': '1px solid #dfe2e5',
      padding: '8px 12px',
      'text-align': 'left',
    },
    td: {
      border: '1px solid #dfe2e5',
      padding: '8px 12px',
    },
    'tr-alt': { 'background-color': '#fafbfc' },
    hr: { border: 'none', 'border-top': '1px solid #eaecef', 'margin-top': '24px', 'margin-bottom': '24px' },
    ul: { 'margin-top': '0', 'margin-bottom': '16px', 'padding-left': '24px' },
    ol: { 'margin-top': '0', 'margin-bottom': '16px', 'padding-left': '24px' },
    li: { 'margin-bottom': '6px' },
    img: { 'max-width': '100%', 'border-radius': '6px', 'margin-top': '4px', 'margin-bottom': '16px' },
    task: { color: '#576b95', 'margin-right': '6px' },
    toc: {
      'background-color': '#fafbfc',
      border: '1px solid #eaecef',
      'border-radius': '8px',
      padding: '16px 20px',
      'margin-bottom': '24px',
      'font-size': '14px',
    },
    card: {
      box: {
        'border-left': '4px solid',
        'border-radius': '8px',
        padding: '14px 16px',
        'margin-top': '0',
        'margin-bottom': '16px',
        'line-height': '1.7',
      },
      title: { 'font-weight': '700', 'font-size': '15px', display: 'block', 'margin-bottom': '6px' },
      quote: {
        'font-size': '30px',
        'line-height': '0.6',
        'font-family': 'Georgia, "Songti SC", serif',
        'margin-right': '4px',
        display: 'inline-block',
        'vertical-align': '-5px',
      },
      kinds: {
        tip: { accent: '#16a34a', bg: 'rgba(22,163,74,0.09)' },
        warning: { accent: '#d97706', bg: 'rgba(217,119,6,0.09)' },
        note: { accent: '#2563eb', bg: 'rgba(37,99,235,0.09)' },
        danger: { accent: '#dc2626', bg: 'rgba(220,38,38,0.09)' },
        quote: { accent: '#6f42c1', bg: 'rgba(111,66,193,0.07)' },
      },
    },
  },

  /**
   * paper — 纸感暖调
   * 适合文艺类公众号 / 随笔，米色背景 + 衬线标题
   */
  paper: {
    id: 'paper',
    name: 'Paper 纸感',
    container: {
      color: '#3e3a34',
      'font-family':
        '"Songti SC", "Noto Serif SC", "STSong", "SimSun", serif',
      'font-size': '16px',
      'line-height': '1.9',
      'letter-spacing': '0.5px',
    },
    heading: {
      color: '#2f2a24',
      'font-weight': '700',
      'line-height': '1.4',
      'margin-top': '32px',
      'margin-bottom': '16px',
    },
    h1: { 'font-size': '26px' },
    h2: { 'font-size': '22px' },
    h3: { 'font-size': '19px' },
    h4: { 'font-size': '17px' },
    h5: { 'font-size': '16px' },
    h6: { 'font-size': '15px' },
    paragraph: { 'margin-top': '0', 'margin-bottom': '18px', 'text-align': 'justify' },
    strong: { color: '#2f2a24', 'font-weight': '700' },
    em: { 'font-style': 'italic' },
    del: { 'text-decoration': 'line-through', color: '#a09a90' },
    link: { color: '#8a6d3b', 'text-decoration': 'underline', 'word-break': 'break-all' },
    'inline-code': {
      color: '#9a3e2f',
      'background-color': '#f5efe6',
      'font-family': '"SFMono-Regular", Consolas, monospace',
      'font-size': '90%',
      padding: '2px 5px',
      'border-radius': '3px',
    },
    codeblock: {
      'background-color': '#f5efe6',
      'font-family': '"SFMono-Regular", Consolas, monospace',
      'font-size': '13px',
      'line-height': '1.7',
      padding: '16px 18px',
      'border-radius': '8px',
      'overflow-x': 'auto',
      color: '#3e3a34',
      'margin-top': '0',
      'margin-bottom': '18px',
      border: '1px solid #e8dfd0',
    },
    blockquote: {
      'border-left': '4px solid #d9c9a8',
      'background-color': '#faf6ee',
      color: '#7a7266',
      padding: '14px 18px',
      'border-radius': '0 8px 8px 0',
      'margin-top': '0',
      'margin-bottom': '18px',
    },
    table: {
      'border-collapse': 'collapse',
      width: '100%',
      'font-size': '14px',
      'margin-top': '0',
      'margin-bottom': '18px',
    },
    th: {
      'background-color': '#f0e8d8',
      color: '#3e3a34',
      'font-weight': '700',
      border: '1px solid #ddd2bc',
      padding: '8px 12px',
      'text-align': 'left',
    },
    td: { border: '1px solid #ddd2bc', padding: '8px 12px' },
    'tr-alt': { 'background-color': '#faf7f0' },
    hr: { border: 'none', 'border-top': '1px solid #ddd2bc', 'margin-top': '28px', 'margin-bottom': '28px' },
    ul: { 'margin-top': '0', 'margin-bottom': '18px', 'padding-left': '24px' },
    ol: { 'margin-top': '0', 'margin-bottom': '18px', 'padding-left': '24px' },
    li: { 'margin-bottom': '6px' },
    img: { 'max-width': '100%', 'border-radius': '4px', 'margin-top': '4px', 'margin-bottom': '18px' },
    task: { color: '#8a6d3b', 'margin-right': '6px' },
    toc: {
      'background-color': '#faf6ee',
      border: '1px solid #e8dfd0',
      'border-radius': '8px',
      padding: '16px 20px',
      'margin-bottom': '28px',
      'font-size': '14px',
    },
    card: {
      box: {
        'border-left': '4px solid',
        'border-radius': '8px',
        padding: '16px 18px',
        'margin-top': '0',
        'margin-bottom': '18px',
        'line-height': '1.8',
      },
      title: { 'font-weight': '700', 'font-size': '16px', display: 'block', 'margin-bottom': '6px' },
      quote: {
        'font-size': '32px',
        'line-height': '0.6',
        'font-family': 'Georgia, "Songti SC", serif',
        'margin-right': '4px',
        display: 'inline-block',
        'vertical-align': '-6px',
      },
      kinds: {
        tip: { accent: '#5c8a4e', bg: 'rgba(92,138,78,0.10)' },
        warning: { accent: '#b07f2a', bg: 'rgba(176,127,42,0.10)' },
        note: { accent: '#5a7ba8', bg: 'rgba(90,123,168,0.10)' },
        danger: { accent: '#ad4b3c', bg: 'rgba(173,75,60,0.10)' },
        quote: { accent: '#7c6a4f', bg: 'rgba(124,106,79,0.10)' },
      },
    },
  },

  /**
   * dark — 深色
   * 适合技术博客 / 掘金 / CSDN 的深色阅读场景
   */
  dark: {
    id: 'dark',
    name: 'Dark 深色',
    container: {
      color: '#d1d5db',
      'font-family':
        '-apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
      'font-size': '15px',
      'line-height': '1.8',
      'letter-spacing': '0.3px',
    },
    heading: { color: '#f3f4f6', 'font-weight': '700', 'line-height': '1.4', 'margin-top': '28px', 'margin-bottom': '14px' },
    h1: { 'font-size': '24px' },
    h2: { 'font-size': '21px' },
    h3: { 'font-size': '18px' },
    h4: { 'font-size': '16px' },
    h5: { 'font-size': '15px' },
    h6: { 'font-size': '14px' },
    paragraph: { 'margin-top': '0', 'margin-bottom': '16px', 'text-align': 'justify' },
    strong: { color: '#f3f4f6', 'font-weight': '700' },
    em: { 'font-style': 'italic' },
    del: { 'text-decoration': 'line-through', color: '#6b7280' },
    link: { color: '#60a5fa', 'text-decoration': 'none', 'word-break': 'break-all' },
    'inline-code': {
      color: '#f9a8d4',
      'background-color': 'rgba(249,168,212,0.12)',
      'font-family': '"SFMono-Regular", Consolas, monospace',
      'font-size': '90%',
      padding: '2px 5px',
      'border-radius': '3px',
    },
    codeblock: {
      'background-color': '#161b22',
      'font-family': '"SFMono-Regular", Consolas, monospace',
      'font-size': '13px',
      'line-height': '1.6',
      padding: '14px 16px',
      'border-radius': '8px',
      'overflow-x': 'auto',
      color: '#c9d1d9',
      'margin-top': '0',
      'margin-bottom': '16px',
      border: '1px solid #30363d',
    },
    blockquote: {
      'border-left': '4px solid #30363d',
      'background-color': '#161b22',
      color: '#8b949e',
      padding: '12px 16px',
      'border-radius': '0 6px 6px 0',
      'margin-top': '0',
      'margin-bottom': '16px',
    },
    table: { 'border-collapse': 'collapse', width: '100%', 'font-size': '14px', 'margin-top': '0', 'margin-bottom': '16px' },
    th: {
      'background-color': '#161b22',
      color: '#c9d1d9',
      'font-weight': '600',
      border: '1px solid #30363d',
      padding: '8px 12px',
      'text-align': 'left',
    },
    td: { border: '1px solid #30363d', padding: '8px 12px' },
    'tr-alt': { 'background-color': 'rgba(255,255,255,0.02)' },
    hr: { border: 'none', 'border-top': '1px solid #30363d', 'margin-top': '24px', 'margin-bottom': '24px' },
    ul: { 'margin-top': '0', 'margin-bottom': '16px', 'padding-left': '24px' },
    ol: { 'margin-top': '0', 'margin-bottom': '16px', 'padding-left': '24px' },
    li: { 'margin-bottom': '6px' },
    img: { 'max-width': '100%', 'border-radius': '6px', 'margin-top': '4px', 'margin-bottom': '16px' },
    task: { color: '#60a5fa', 'margin-right': '6px' },
    toc: {
      'background-color': '#161b22',
      border: '1px solid #30363d',
      'border-radius': '8px',
      padding: '16px 20px',
      'margin-bottom': '24px',
      'font-size': '14px',
    },
    card: {
      box: {
        'border-left': '4px solid',
        'border-radius': '8px',
        padding: '14px 16px',
        'margin-top': '0',
        'margin-bottom': '16px',
        'line-height': '1.7',
      },
      title: { 'font-weight': '700', 'font-size': '15px', display: 'block', 'margin-bottom': '6px' },
      quote: {
        'font-size': '30px',
        'line-height': '0.6',
        'font-family': 'Georgia, "Songti SC", serif',
        'margin-right': '4px',
        display: 'inline-block',
        'vertical-align': '-5px',
      },
      kinds: {
        tip: { accent: '#4ade80', bg: 'rgba(74,222,128,0.10)' },
        warning: { accent: '#fbbf24', bg: 'rgba(251,191,36,0.10)' },
        note: { accent: '#60a5fa', bg: 'rgba(96,165,250,0.10)' },
        danger: { accent: '#f87171', bg: 'rgba(248,113,113,0.10)' },
        quote: { accent: '#c084fc', bg: 'rgba(192,132,252,0.10)' },
      },
    },
  },
};

export function getTheme(id) {
  return THEMES[id] || THEMES.clean;
}
